### ISSUE TITLE
Did Chrome fix this?

### ISSUE THREAD

**Issue by nirvana-msu** [sp1d3r/swf_json_csrf#17]
I was trying to use this today, and as far as I can tell it no longer works in Chrome. When a 307 (/308) redirect is issued, Chrome simply does not follow it. Network panel does show the entry (with `(cancelled)` status), however this is misleading - the actual request is never fired (which can be verified with burp proxy). What's weird, is that 307 redirect is dropped even if it's issued to the same domain.. 

Would be great if someone could confirm whether this is the case. I've tried quite a few things, including replaying some of the old PoCs I have built, and none of them seem to trigger the request anymore.

**Comment by juniorhero** [comment]
Hi 
I am too having the same error

**Comment by nirvana-msu** [comment]
@juniorhero well, for FireFox it's expected - it has been fixed for some time now (see e.g. references in Readme). They drop 307/308 redirects that were originated from Flash (?) and are cross-origin.

I could not find any public mention of this being fixed in Chrome however. Wondering if that could be a side-effect of some other change they did.

**Comment by juniorhero** [comment]
@nirvana-msu  I too couldn't find any references regarding the chrome fix

but I guess chromium was fixed long back https://bugs.chromium.org/p/chromium/issues/detail?can=2&start=0&num=100&q=&groupby=&sort=&id=425280

I wish if someone else can confirm if this still works in chrome
I am using the latest chrome Version 81.0.4044.138

**Comment by juniorhero** [comment]
@nirvana-msu  did you attempt both GET and POST request?
  Does both doesn't work for you?

**Comment by nirvana-msu** [comment]
@juniorhero It definitely worked in Chrome in Aug 2018 (last time I've used this successfully myself). The bug you referenced is a different issue.

Not sure what you mean by GET, the whole point here is to send POST requests with custom Content-Type (such as `application/json`).

**Comment by juniorhero** [comment]
I have tried to send POST requests with custom Content-Type (such as application/json) and did not work

**Comment by juniorhero** [comment]
@sp1d3r can u confirm ?

**Comment by sp1d3r** [comment]
Yes, I confirm this no longer works in Chrome 81. It worked however in Chrome<=79.
The bugfix you mentioned was related to a bit different behavior.
I guess this technique can be considered as dead for now.
